export const keymap = {
  'a#': 'shift+a',
  'b#': 'shift+b',
  'c#': 'shift+c',
  'd#': 'shift+d',
  'e#': 'shift+e',
  'f#': 'shift+f',
  'g#': 'shift+g',
  'a': 'a',
  'b': 'b',
  'c': 'c',
  'd': 'd',
  'e': 'e',
  'f': 'f',
  'g': 'g',
  'a_': 'alt+a',
  'b_': 'alt+b',
  'c_': 'alt+c',
  'd_': 'alt+d',
  'e_': 'alt+e',
  'f_': 'alt+f',
  'g_': 'alt+g',
}
